name: Auto Deploy to Yandex Storage

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.YC_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.YC_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.YC_REGION }}
      BUCKET_NAME: ${{ secrets.YC_BUCKET }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - run: npm run build

      - run: |
          test -d out || (echo "out folder missing" && exit 1)

      - name: Install AWS CLI
  run: |
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip -q awscliv2.zip
    sudo ./aws/install --update

      - run: |
          aws s3 sync ./out s3://$BUCKET_NAME \
            --endpoint-url https://storage.yandexcloud.net \
            --delete